import { Button, VerticalBox , TextEdit, HorizontalBox, ComboBox} from "std-widgets.slint";

export component CenterBox inherits VerticalBox {
    alignment: center;
    HorizontalBox {
        alignment: center;
        @children
    }
}

export component AppWindow inherits Window {
    in property<[string]> languages;
    in-out property <string> selected-language;
    callback select-language(string);
    callback submit-text(string);

    width: 1280px;
    height: 400px;

    HorizontalLayout {
        CenterBox {
            horizontal-stretch: 1;
            tab-suppressor := FocusScope {
                input := TextEdit {
                    height: 200px;
                    width: 800px;
    
                    text: "";
                    font-size: 40px;
        
                    init => {
                        input.focus();
                    }
                    forward-focus: tab-suppressor;
                }
                key-pressed(event) => {
                    debug(event.text);
                    if (event.text == Key.Tab) {
                        reject
                    } else {
                        accept
                    }
                }
            }

        }
        VerticalBox {
            alignment: space-around;
            horizontal-stretch: 0;
            width: 150px;

            HorizontalBox {
                horizontal-stretch: 0;
                alignment: center;
                ComboBox {
                    height: 30px;
                    width: 100px;
                    model: root.languages;
                    current-value: root.selected-language;
                    selected(value) => {
                        root.select-language(value);
                    }
                }
            }

            HorizontalBox {
                alignment: center;
                Button {
                    width: 75px;
                    height: 75px;
                    text: "Clear";

                    clicked => {
                        input.text = "";
                    }
                }
            }
            submit_button := HorizontalBox {
                alignment: center;
                Button {
                    width: 75px;
                    height: 75px;
                    text: "Submit";
                    enabled: input.text != "";
                    clicked => {
                        if (input.text != "") {
                            root.submit-text(input.text);
                            input.text = "";
                        }
                    }
                }
            }
        }

    }
}
