name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true
          targets: aarch64-unknown-linux-gnu

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu
        
      - name: Package
        id: package
        uses: jiro4989/build-deb-action@v3
        with:
          package: last-snow
          package_root: target/aarch64-unknown-linux-gnu/release
          maintainer: krokosik
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'arm64'
          depends: 'libxcb-shape0-dev, libxcb-xfixes0-dev, libxkbcommon-dev, libfontconfig-dev, clang, libavcodec-dev, libavformat-dev, libavutil-dev, libavfilter-dev, libavdevice-dev, libasound2-dev, pkg-config'
          desc: 'Last Snow Input + Display'

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: ${{ steps.package.outputs.file_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
